theme: jekyll-theme-minimal

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Dreams are real"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Karim"
description              : "AI, arts and personal portfolio"
